### ISSUE TITLE
The problem with Russian characters

### ISSUE THREAD

**Issue by afuno** [AtomLinter/linter-ruby#104]
Just two screenshots that demonstrate and describe the situation as much as possible:

Good: [screenshot 1](https://habrastorage.org/files/de0/7aa/47c/de07aa47c6854ad1ba85b63b53d96f31.png)

Bad: [screenshot 2](https://habrastorage.org/files/5fd/490/e29/5fd490e29f9c4040ba9369c33c59a0b0.png)

The problem in the encoding of the text.

**Comment by Arcanemagus** [comment]
Marking as a duplicate of #103, which has the fix for this on your end, although we still need to figure out why it stopped working correctly when it was fixed.
