### ISSUE TITLE
Not picking up method calls?

### ISSUE THREAD

**Issue by pookah-net** [AtomLinter/linter-ruby#108]
I've got this code:

```ruby
# A reference to the File class for this file.
  attr_reader :file_reference
  alias :file :file_reference

  # Private method to set the File class reference.
  attr_writer :file_reference
  private :file_reference=

  # Private short-cut to clear the file reference.
  def clear_file_reference
    file_reference = nil
  end
  private :clear_file_reference
```
In `clear_file_reference`, linter-ruby keeps warning me I've got an "assigned but unused variable". I can't get rid of the warning! I've tried removing the `private` call. The only thing that works is `@file_reference = nil`.

Is there some setting I'm missing? 

(Using linter-ruby 1.2.4)

Thanks!
Ian

**Comment by Arcanemagus** [comment]
If you run `ruby -wc file.rb` in the CLI do you see the same issues? This package is just a wrapper around that.

**Comment by pookah-net** [comment]
Sorry... I forgot about this one!

Yes, I get the same result. I simply call the instance variable to stop the error message.

**Comment by Arcanemagus** [comment]
If you are getting the same result from that, then everything is working as it should 😛.
