### ISSUE TITLE
Ruby 2.4

### ISSUE THREAD

**Issue by slava-dzyba** [AtomLinter/linter-ruby#109]
Hi.

First of all, thank you very much for this linter! I'm happy to use it.
But I have an issue running the linter with Ruby 2.4. Looks like it's just not working.
Yet on the same Atom configuration (Atom 1.13 with sync-settings plugin) but on Ruby 2.3.1 it works just fine.

Regards,
Slava

**Comment by Arcanemagus** [comment]
Can you post the output of running `ruby -wc -Eutf-8` on one of the files it's not working on? I'm betting the output format got changed in Ruby 2.4.

**Comment by slava-dzyba** [comment]
```
app/controllers/countries_controller.rb:9: warning: mismatched indentations at 'end' with 'def' at 6
app/controllers/countries_controller.rb:9: syntax error, unexpected end-of-input, expecting keyword_end
```

**Comment by slava-dzyba** [comment]
Looks like it didn't changed, but still I've just switched back to 2.3.1 and linter works, again to 2.4.0 - not working.

**Comment by slava-dzyba** [comment]
My bad.
Switching system-wide ruby version to 2.3.1 and then back to 2.4.0 actually helped. Now it works.
Sorry for bothering.

**Comment by Arcanemagus** [comment]
No worries, if it crops up again feel free to reopen the issue!
