### ISSUE TITLE
Inefficient error reporting when string contains German letters

### ISSUE THREAD

**Issue by amed-kino** [AtomLinter/linter-ruby#111]
Atom 1.15.0
Linter 1.11.23
Linter-Ruby 1.2.5

This error showing in rspec 
![image](https://cloud.githubusercontent.com/assets/5637272/23847293/08b10092-07d2-11e7-995e-2eefd488d158.png)

**Comment by Arcanemagus** [comment]
Most likely this is a duplicate of #103.
