### ISSUE TITLE
Documentation of how to disable

### ISSUE THREAD

**Issue by timscott** [AtomLinter/linter-ruby#118]
How do I disable a rule for particular code? For example, with eslint you do like this:

```javascript
// eslint-disable-next-line no-unused-expressions
```

I'm not finding the documentation of how to accomplish this with `linter-ruby`.

**Comment by Arcanemagus** [comment]
`linter-ruby` doesn't _have_ "rules". This is literally the equivalent of running `ruby -wc foo.rb`. If you are getting messages from this provider they are coming directly from the Ruby runtime so you _really_ should fix them.
