### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by envygeeks** [AtomLinter/linter-ruby#13]
There hasn't been an update for nearly a year and nothing is happening about the deprecation before 1.0 happens which means this package will stop working... If you need help please just say so.

**Comment by hd-deman** [comment]
yes, it's hard to support over 30 linters ::) How can you help?

**Comment by envygeeks** [comment]
I can program?

**Comment by envygeeks** [comment]
If you need somebody to help maintain this repo let me know, I'm happy to maintain it for you because I'm a heavy Ruby programmer and love this addon so I would hate for it to fall to demise when I can help keep it up.  I'm not the best Coffeescript programmer but I should be alright enough to help out here.
