### ISSUE TITLE
No linting occurs

### ISSUE THREAD

**Issue by drewprice** [AtomLinter/linter-ruby#22]
I've installed & uninstalled linters (both the Atom linter & linter-ruby), as well as Atom itself, but I still cannot get the linter to catch any errors. 

<img width="1280" alt="screenshot 2015-08-06 23 55 38" src="https://cloud.githubusercontent.com/assets/7977907/9128481/5f25215e-3c97-11e5-82e5-d566bcc1b4a1.png">

Obviously, running the ruby-lint gem catches this as an error, but I get nothing in the editor. The executable path is set to `/Users/drew/.rvm/rubies/ruby-2.2.2/bin/ruby`.

I'm having the same issue with linter-rubocop—so maybe it's any issue with Linter itself?

Thanks!

**Comment by drewprice** [comment]
Resolved [here](https://github.com/atom-community/linter/issues/815#issuecomment-128594402). Thanks.

**Comment by k2b6s9j** [comment]
Actually. I just published a real fix. Downgrading the Core Linter is really only a duct tape solution.

**Comment by drewprice** [comment]
Even better—thank you!

**Comment by Arcanemagus** [comment]
Hence the "working temporarily" :wink:. Thanks for updating this @k2b6s9j!
