### ISSUE TITLE
Failed to spawn command ruby. Make sure ruby is installed and on your PATH

### ISSUE THREAD

**Issue by Infectsoldier** [AtomLinter/linter-ruby#25]
After last commit i got error
`Failed to spawn command ruby. Make sure ruby is installed and on your PATH
[object Object]`

Before this its work fine

**Comment by Infectsoldier** [comment]
Add this to conf:
`'linter-ruby':
    'rubyExecutablePath': 'C:\\Ruby21\\bin\\ruby.exe'`
But still didnt work
`Make sure C:\Ruby21\bin\ruby.exe is installed and on your PATH`
Added to path

**Comment by TG-KK** [comment]
same here

**Comment by steelbrain** [comment]
I have never used `config.cson` but setting the path from settings view should to that.

**Comment by steelbrain** [comment]
Also, are you able to repro on master branch?
```
mv ~/.atom/packages/linter-ruby /tmp
git clone https://github.com/AtomLinter/linter-ruby ~/.atom/packages/linter-ruby
cd ~/.atom/packages/linter-ruby
apm install
```

**Comment by Infectsoldier** [comment]
Thank you steelbrain,
now its work fine
