### ISSUE TITLE
linter-ruby does not support Lint on the fly

### ISSUE THREAD

**Issue by mneumark** [AtomLinter/linter-ruby#27]
I have been holding off on updating for a while due to `linter-ruby` not being upgraded for `linter 1.3`. Then there was an update, but it was broken. Finally this morning it's working again, but it only seems to lint when I save the file.

I checked my settings under linter and sure enough Lint on the fly is checked.

I checked in with the `linter` folks and was informed its a problem with `linter-ruby`:
atom-community/linter#824

They said it SAYS `linter-ruby` supports lintOnFly, but it only passes linter the current file name so it can only be used as lintOnSave as currently written.

**Comment by mneumark** [comment]
I suppose it'd have to `try/catch` running the code from `activeEditor.getText()` through the linter.

**Comment by Arcanemagus** [comment]
If the linter itself supports getting the input from `stdin` all you need to do is add `stdin: text` to the options on line 45, and grab the text contents before that with getText() as @mneumark said.

**Comment by Arcanemagus** [comment]
If it doesn't support `stdin` input... then things get tricky as you would need to generate a temporary file to lint on and handle cleaning it up afterwards.

**Comment by mneumark** [comment]
Don't you need to make a separate `helpers.exec` call for the `stdin` version versus the saved copy version?

**Comment by Arcanemagus** [comment]
Actually... that's a good point. @steelbrain does `linter` just make a call to the linter provider with the current contents on save?

If lintOnFly is working it should have already caught any changes, but I'm not positive. No linter that does lintOnFly has a separate call though.

**Comment by mneumark** [comment]
I guess I'll close this since it seems the fix for this was merged (and just not released yet).
