### ISSUE TITLE
No warnings and line numbers are offset

### ISSUE THREAD

**Issue by mneumark** [AtomLinter/linter-ruby#33]
I noticed that ever since the last update there are no longer warnings. This seems due to the move to a broader regex, as it does not identify type any longer. I think this needs to be added back in.

Additionally (on a Mac anyways) my line numbers are offset by one. If the error was on line 376, the linter is telling me the error is on line 377, despite the fact that running ruby -cw in the terminal on the same file provides correct line numbers.

I'm going to see if I have time to put in my own PR to fix it but I thought I would formally inform the community.

**Comment by Project0** [comment]
line number should be fixed within the pull request #30 
Messages are currently hard coded to 'error', this needs to be fixed.
