### ISSUE TITLE
always mark the same error

### ISSUE THREAD

**Issue by Kvothe11011** [AtomLinter/linter-ruby#34]
if i wanna save mi work, always says in the same line no matter if i change the code, always mark that warning in the same lines ( 6 and 7)

warning: assigne but unused variable

**Comment by Project0** [comment]
please try with new release. I fixed the line position in the last pull request. 
Do you have an code example for your problem (Probably this is fixed as well, lintonfly does work now)

**Comment by Kvothe11011** [comment]
it seems that is already work well, i already tasted and work perfectly thanks for fixed the bug, this help the people like me that it's beginning in ruby, thanks a lot
