### ISSUE TITLE
All issue markers are offset down by one line

### ISSUE THREAD

**Issue by Zer0t3ch** [AtomLinter/linter-ruby#36]
https://i.imgur.com/f92AqL8.png

**Comment by steelbrain** [comment]
cc @k2b6s9j

**Comment by k2b6s9j** [comment]
Beautiful. I'll look at it sometime tomorrow afternoon.

**Comment by k2b6s9j** [comment]
Mind testing again? I just publish an update that might fix this.

**Comment by Zer0t3ch** [comment]
Just tested. No change.

Also, I didn't mention it before because it seemed unrelated, but I occasionally get an error pop-up while editing. (rather than when saving, which is odd)

https://i.imgur.com/q0slrrb.png

Just updated, this is with linter-ruby version 1.1.1

**Comment by Arcanemagus** [comment]
@Zer0t3ch can you check the latest version? Your error you were seeing is an internal Atom bug that is worked around in recent `atom-linter` versions, the off-by-one line issue though looks like it shouldn't be happening...

**Comment by Zer0t3ch** [comment]
@Arcanemagus The current version doesn't seem to have the issue any more, but I'm also testing on an entirely different system. (Windows as opposed to *nix) I can open a new issue if I encounter it again.

**Comment by Arcanemagus** [comment]
Thanks for the reply! Marking this as closed.
