### ISSUE TITLE
Linter mis-identifies a required keyword argument as a syntax error

### ISSUE THREAD

**Issue by ansonhoyt** [AtomLinter/linter-ruby#47]
I think I found a bug. I defined a method with a keyword argument, but no default value, which makes it a required argument.

```ruby
class Activities::AncestorsQuery
  def initialize(activities:)
  end
end
```

This is valid as of Ruby 2.1, per (https://robots.thoughtbot.com/ruby-2-keyword-arguments). However, the linter falsely identifies a syntax error:
![screen shot 2015-11-17 at 2 14 41 pm](https://cloud.githubusercontent.com/assets/543751/11222112/926bcc62-8d36-11e5-8f6b-2ac626558760.png)

The class works fine from my console. They keyword is required, and the class initializes when it is provided:
![screen shot 2015-11-17 at 2 23 26 pm](https://cloud.githubusercontent.com/assets/543751/11222157/d190b3da-8d36-11e5-9ddb-dc8361189752.png)

**Comment by Arcanemagus** [comment]
If you run `ruby -wc <filename>` on the file do you get the same error?

**Comment by ansonhoyt** [comment]
No, I get "Syntax OK".

```bash
~/code/tiu/p2p-database $ ruby -wc app/queries/activities/ancestors_query.rb
Syntax OK
```

I do have several rubies managed with RVM. I didn't have anything configured for Ruby Exception Path, and when I changed this to the output of `which ruby`, the error goes away.
```bash
~/code/tiu/p2p-database $ which ruby
/Users/ahoyt/.rvm/rubies/ruby-2.2.1/bin/ruby
~/code/tiu/p2p-database $ cat .ruby-version
ruby-2.2.1
```

So it looks like the linter is working beautifully, but I'm not getting it the right ruby. I'm not sure where linter-ruby determines it's ruby version, but it doesn't seem to know about determining a folder's ruby via RVM or `.ruby-version` files.

I can't just use Ruby Exception Path, since that is global and I have different rubies per-project.

**Comment by Arcanemagus** [comment]
You would either need to launch Atom from within the environment that has the path set properly so that `ruby` resolves to the right one, or manually specify the path in the settings.

**Comment by ansonhoyt** [comment]
I still get the error when I launch ruby from the desired folder, though the path is correct from this folder:

```bash
~/code/tiu/p2p-database $ atom .
~/code/tiu/p2p-database $ which ruby
/Users/ahoyt/.rvm/rubies/ruby-2.2.1/bin/ruby
```

(This is the path that makes everything work if I use it for `Ruby Exception Path`.)

**Comment by ansonhoyt** [comment]
You have it straight, though my last comment was a bit mixed up! (replaced "ruby" and "Exception" above)

I thought I was getting the syntax error after fully closing Atom and re-launching from the terminal in `~/code/tiu/p2p-database`, but today it's all rainbows and "Syntax OK".

I'll try not to get mixed up this time...

When I launch atom from a terminal with ruby 2.2.1 in the path, it correctly gives "Syntax OK"
```bash
# quit Atom application
~/code/tiu/p2p-database $ which ruby
/Users/ahoyt/.rvm/rubies/ruby-2.2.1/bin/ruby
~/code/tiu/p2p-database $ ruby -wc /Users/ahoyt/code/tiu/p2p-database/app/queries/activities/ancestors_query.rb
Syntax OK
~/code/tiu/p2p-database $ atom .
# no linter errors, which is correct for ruby 2.1+
```

When I launch atom from a terminal with ruby 2.0.0 in the path, it correctly (for ruby 2.0) gives a Syntax error:
```bash
# quit Atom application
~/code/tiu/p2p-database $ rvm use 2.0
Using /Users/ahoyt/.rvm/gems/ruby-2.0.0-p643
~/code/tiu/p2p-database $ which ruby
/Users/ahoyt/.rvm/rubies/ruby-2.0.0-p643/bin/ruby
~/code/tiu/p2p-database $ atom .
# correct linter errors for ruby 2.0
```

So Atom does seem to be picking up the ruby version from the terminal where I launch it. I had multiple projects open yesterday, so am guessing that I had first launched Atom from a pre-2.1 terminal, then the other window later for a post-2.1 terminal. Doesn't seem like a bug, though it would be cool if Atom had a way to allowed multiple windows/projects where each has one a different ruby, and it would keep it straight when relaunching Atom after a reboot (and all the projects re-open).

Thanks so much for bearing with me. This has been a super helpful project! Closing this issue.

**Comment by Arcanemagus** [comment]
Atom inherits its environment from the environment it is first launched from, and new windows are spawned from that first instance. Unfortunately I don't know of a way to specify the right environment to launch the right `ruby` since we have no reference to it :disappointed:.

A workaround that involves a bit of work and extra configuration but would let you keep things all in one place would be to create a wrapper script that checks the path it is being called to lint and then runs the proper `ruby` for that path. The downside of this is keeping it maintained...

**Comment by ansonhoyt** [comment]
The way it works now makes sense (Principal of Least Surprise). Thanks again for helping me understand what was happening...and for maintaining this very helpful tool.
