### ISSUE TITLE
Possible false-positive - string symbol syntax

### ISSUE THREAD

**Issue by alauper** [AtomLinter/linter-ruby#48]
The following doesn't report any lint errors:

`{ valid: 'syntax' }`

But this does

`{ 'valid': 'syntax' }`

Both are valid and shouldn't be reported as an error.

Also, if I install the ruby-lint gem and run it against this same syntax, I don't see any errors.  So I'm not sure why I'm seeing it in the Atom editor as such.

**Comment by Arcanemagus** [comment]
Perhaps you have a different ruby version in the environment Atom runs from than the one that you tested in the CLI with? Try closing all Atom instances, and then launching Atom from the same terminal that you do not see any syntax error from.

**Comment by alauper** [comment]
Sorry, my issue isn't that I see two different results.  The issue I'm submitting is that AtomLinter is reporting a false error.  { 'this_is_valid': 'syntax' }.  AtomLinter should not report that as an error.

**Comment by Arcanemagus** [comment]
`linter-ruby` only forwards on the messages it gets from running `ruby -wc` on the current file. So the results from what you see within Atom and what you see from running `ruby -wc foo.rb` _should_ be identical.

The only cases that I have seen where they are not are when there are different versions of `ruby` installed on the system and Atom was launched from an environment that was using the wrong one.

**Comment by Arcanemagus** [comment]
Marking as closed due to lack of response, if you have any further issues please feel free to comment!

**Comment by alauper** [comment]
I think this was related to [issue 77](https://github.com/AtomLinter/linter-ruby/issues/77).
