### ISSUE TITLE
unexpected hash syntax

### ISSUE THREAD

**Issue by binary1101** [AtomLinter/linter-ruby#71]
`gem 'therubyracer', platforms: :ruby`

> Ruby syntax error unexpected ':', expecting $end

![gemfile_ __volumes_u_2_projects_dota2farm_server](https://cloud.githubusercontent.com/assets/2002920/13201875/9f143df4-d8a5-11e5-9c8c-cb42bd7725b6.png)

Using
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin12.0]
rvm 1.26.11 (latest)

**Comment by binary1101** [comment]
fixed by setting 
```
"linter-ruby":
    rubyExecutablePath: "/Users/binary/.rvm/rubies/ruby-2.2.4/bin/ruby"
```
Is there any way to make it works automatically with different projects and rvm?

**Comment by Arcanemagus** [comment]
Really the only reliable way is to close all instances of Atom and launch it from a terminal that is in the desired environment.
