### ISSUE TITLE
Ruby 2.3.0 support

### ISSUE THREAD

**Issue by stefankp** [AtomLinter/linter-ruby#77]
I rely on your linter every day, it does an amazing job! However, since upgrading to Ruby 2.3.0 I get syntax errors, specifically for the `lonely operator`. Is Ruby 2.3.0 support planned for the next release?

**Comment by Arcanemagus** [comment]
What error exactly are you seeing? This linter essentially just runs `ruby -wc -Ku foo.rb`, and returns the results...

**Comment by stefankp** [comment]
It's a syntax error for the `.` after `&`
![image](https://cloud.githubusercontent.com/assets/3661203/13645923/14335e94-e625-11e5-9872-322c464aa696.png)

**Comment by Arcanemagus** [comment]
That's coming directly from `ruby`, nothing to do with the plugin :stuck_out_tongue:

You can confirm by running the above command on your file in a terminal.

**Comment by stefankp** [comment]
Just did that and it says `Syntax OK`

**Comment by Arcanemagus** [comment]
Hmmm, is it possible that Atom is running an older version of `ruby`? What OS are you on?

**Comment by stefankp** [comment]
I have `Mac OS 10.11.3` and `Atom 1.5.4`

**Comment by Arcanemagus** [comment]
If you run `which ruby`, verify that the `ruby` pointed to there is v2.3.0, and put that path into the Executable Path does it fix the error showing up?

**Comment by stefankp** [comment]
No, still getting errors. If this is not related to the plugin, then I'll figure it out. I don't want to keep you busy. Thanks for your help :+1:

**Comment by Arcanemagus** [comment]
Well, it's somehow related if the plugin is showing it but `ruby` in the terminal isn't.

**Comment by Arcanemagus** [comment]
Can you open Atom's developer tools, find the `main.js` file of this package, and place a breakpoint [here](https://github.com/AtomLinter/linter-ruby/blob/v1.2.2/lib/main.js#L35).

Then open a Ruby file (with developer tools open) and you should hit that breakpoint, save the file to trigger a lint if not. Once you are at the breakpoint run this in the console inside Developer Tools:
```js
out = helpers.exec(command, ['-v'])
```
And then allow the breakpoint to continue.

After a tiny bit (should be done by the time you click to continue the breakpoint), type `out` again to see the result of running `ruby -v` inside Atom.

**Comment by stefankp** [comment]
aha `ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]`. Now it starts to make sense ... wow

**Comment by Arcanemagus** [comment]
Are you seeing that even when you set the full path to the ruby you are using in the terminal?

**Comment by stefankp** [comment]
Yes, but maybe I am doing it wrong: 
My ruby is at `/Users/username/.rbenv/shims/ruby` and I added `export PATH="/Users/username/.rbenv/shims/ruby:$PATH"`. I can see it in `$PATH` ...

**Comment by Arcanemagus** [comment]
Can you try re-installing linter-ruby? It looks like the minimum version of the helper library that runs the `ruby` program might not have the latest sets of workarounds for OS X giving GUI applications a blank environment. Reinstalling should update it to the current version.

**Comment by stefankp** [comment]
Same thing

**Comment by Arcanemagus** [comment]
Just to confirm that it's loading the right library, can you do a `npm list --depth=0` from the `~/.atom/package/linter-ruby` directory? And if you have any other linter plugins either re-install them or temporarily disable them to ensure that Atom loads the current libary.

**Comment by stefankp** [comment]
```
linter-ruby@1.2.2 /Users/username/.atom/packages/linter-ruby
├── atom-linter@4.6.1
└── atom-package-deps@4.0.1
```

**Comment by stefankp** [comment]
There is of course also the possibility that this syntax `@object&.instance_method(parameter)` is indeed wrong ...

**Comment by Arcanemagus** [comment]
Well, in a terminal where `ruby -v` reports 2.3.0, does `ruby -wc foo.rb` show Syntax OK?

**Comment by stefankp** [comment]
Yes

**Comment by Arcanemagus** [comment]
@steelbrain What steps should we take to debug why `consistent-env` isn't grabbing the right environment?

**Comment by steelbrain** [comment]
@Arcanemagus We would check for the shell name and then source the shell files in a terminal and see if we get an error, something like `($SHELL -ic "env;exit");` in a terminal

**Comment by stefankp** [comment]
Ok I fixed it:

I looked in `config.cson` and `"linter-ruby": {}` had no settings set. I added 
```
"linter-ruby":
    rubyExecutablePath: "/Users/username/.rbenv/shims/ruby"
``` 
and it works now :+1: 

Thanks for your help, this can be closed :+1:

**Comment by alauper** [comment]
uninstalling linter-ruby plugin, reinstalling the plugin, and then restarting atom fixed the issue for me.
