### ISSUE TITLE
Error: spawn ruby ENOENT

### ISSUE THREAD

**Issue by kodburn** [AtomLinter/linter-ruby#80]
Getting this error:
```text
Error: spawn ruby ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

The error doesn't appear if I open Atom from the directory of the project using Terminal.

**Comment by Arcanemagus** [comment]
What OS are you on?

**Comment by kodburn** [comment]
Hi, I am on Ubuntu 15.10.

**Comment by kodburn** [comment]
I am on Ubuntu 15.10

**Comment by Arcanemagus** [comment]
If you put the output of `which ruby` into the Executable path setting does this error go away?

**Comment by kodburn** [comment]
Doesn't help. Have the same issue with rubocop and scss-lint. They work
fine from terminal, but I get errors when trying to open .scss or .rb files
in Atom

**Comment by kodburn** [comment]
But when I open Terminal, go to my projects folder, and open atom using command 'atom /project_name' everything works good -- ruby-linter, rubocop and scss-linter are working without any issues

**Comment by kodburn** [comment]
I've added ruby-linter, rubocop and scss-linter into the Executable path, but it doesn't help

**Comment by Arcanemagus** [comment]
So if you put `/usr/bin/ruby` into the Executable Path setting it still doesn't work?

**Comment by kodburn** [comment]
Yes, it doesn't

**Comment by Arcanemagus** [comment]
Okay, let's back up a step:

* What exactly do you get from `which ruby` in a terminal (where if you launched Atom, it would work)?
* What is the _exact_ error you see when you have the output of the above entered into the Executable Path setting?

**Comment by kodburn** [comment]
This is the output of `which ruby` command: ` /home/kodburn/.rvm/rubies/ruby-2.3.0/bin/ruby`
It works if I launch Atom from this folder:` /home/kodburn/Documents/Projects`
This is the error I get: 
```
Error: spawn ruby ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

**Comment by kodburn** [comment]
It is the output of the `echo $PATH` command:
`home/kodburn/.rvm/gems/ruby-2.3.0/bin:/home/kodburn/.rvm/gems/ruby-2.3.0@global/bin:/home/kodburn/.rvm/rubies/ruby-2.3.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/kodburn/.rvm/bin:/home/kodburn/.rvm/bin:/home/kodburn/.rvm/bin:/usr/bin/ruby
`

**Comment by kodburn** [comment]
As you see I have added ruby to the $PATH multiple times

**Comment by antmachine** [comment]
Same error here. Ruby 2.3.1 is in $PATH via .rvm. Running Ubuntu 16.04.1 with kernel 4.4.0-34-generic.

**Comment by antmachine** [comment]
``Error: spawn ruby ENOENT
``Error: spawn ruby ENOENT
``at exports._errnoException (util.js:890:11)
``at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
``at onErrorNT (internal/child_process.js:348:16)
``at _combinedTickCallback (internal/process/next_tick.js:74:11)
``at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by camelscript** [comment]
Here is how i got mine working. In terminal run: "which ruby". The output paste in Linter package's "Ruby Exacutable Path" settings field. Done.

**Comment by Xeboc** [comment]
Also getting this error in Windows 10.  Fixed by installing Ruby and adding to the path.  This error probably just needs to be caught with a 'Hey, is ruby installed and in your path?' message.

```
Error: spawn ruby ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Arcanemagus** [comment]
@Xeboc can you file an issue on [sb-exec](https://github.com/steelbrain/exec/issues) about the message? I thought it was already supposed to be handling this, but it looks like it isn't right now.

For those of you using RVM, you _must_ launch Atom from a terminal in the proper directory. RVM does "funky" things to the shell in order to work it's magic which we can't emulate easily within Atom.

For those of you who haven't installed Ruby yet well... there's your answer 😛.

Marking this issue as closed, feel free to continue the discussion here or file a new issue if you are still having problems.
