### ISSUE TITLE
Ignore lint 

### ISSUE THREAD

**Issue by Ashley-Pettit** [AtomLinter/linter-ruby#81]
Hey guys,

It would be great if you could ignore a lint on a one by one as well as 'type' basis.

I know it could be done via the setting "for a type" warning hard removal but a nice interface to choose the warnings you want would be cool. 

If I get time I'll code it up :)

**Comment by Arcanemagus** [comment]
If I'm understanding what you are asking correctly, I think you need to file this on [linter-ui-default](https://github.com/steelbrain/linter-ui-default). This package has absolutely nothing to do with the interface the user sees, it's just a translator from `ruby -wc` to messages `linter` understands.
