### ISSUE TITLE
Settings — Include extensions

### ISSUE THREAD

**Issue by roolo** [AtomLinter/linter-ruby#93]
<img width="577" alt="atom_-_ruby_linter" src="https://cloud.githubusercontent.com/assets/173141/18474379/0e7512e6-79c2-11e6-8511-88eea5fbbbac.png">

Please add option to set included extensions. The image above reports Ruby syntax error in Terraform file. It seems to me more user friendly to tell "use this linter just for .rb", than having to explicitly turn it off for all the other extensions (currently there is option to ignore some extensions).

**Comment by Arcanemagus** [comment]
I'm not sure what you are talking about here... file extensions?

This linter is only tangentially related to the file extension. It specifies the _scopes_ that it knows how to handle [here](https://github.com/AtomLinter/linter-ruby/blob/v1.2.2/lib/main.js#L30). A language package (`language-ruby`) is what determines how mapping between a file extension and a scope happens. It sounds like you are using a Terraform file, so I would look at whatever language package you have providing syntax highlighting for that, and potentially file a bug with them having them change the scope from a Ruby scope.

**Comment by Arcanemagus** [comment]
Marking this as closed, if a language package is marking code as `source.ruby` that shouldn't be, then this is a bug in that language file.

There is already a setting to exclude certain file extensions that would otherwise be ran, possibly for bizarre edge cases like this.
