### ISSUE TITLE
Improve visibility of syntax errors

### ISSUE THREAD

**Issue by sandstrom** [AtomLinter/linter-ruby#94]
Currently the normal errors are easy to see, but syntax errors are almost invisible.

Great if syntax errors could get the same prominence as warnings.

**Normal error**

![image](https://cloud.githubusercontent.com/assets/122287/18882037/e8d88c8a-84dd-11e6-82a2-0f9aaedc11a4.png)

**Syntax error**

![image](https://cloud.githubusercontent.com/assets/122287/18882068/09ad4568-84de-11e6-9570-6acfaefe175c.png)

**Comment by Arcanemagus** [comment]
This should be fixed in v1.2.4!
