### ISSUE TITLE
Linter Not Activating

### ISSUE THREAD

**Issue by ryanchuleff** [AtomLinter/linter-ruby#96]
I'm new to the Atom community so I apologize in advance if I fail to follow guidelines.

I have a fresh copy of Atom installed on OSX, and I've just installed the linter-ruby package.

I have linter-ruby v1.2.3, and linter v1.11.18 installed.

When I open a Ruby file (extension .rb and showing 'Ruby' as the language in the lower right corner), if I make an obvious syntax exception the linter doesn't trigger and the lower left hand corner says "No Issues"

If I run ruby -wc in the terminal on the same file, it catches the syntax error and outputs it to the terminal.

Clearly I must be doing something wrong as it appears the linter is not triggering automatically on my files.  What can I do to debug this further or resolve what the problem might be?

**Comment by Arcanemagus** [comment]
It's likely this is a bug in the new "delayed activation", I'll add the other likely language file...

**Comment by Arcanemagus** [comment]
This should be fixed in v1.2.4, if it isn't please let me know!
